### ISSUE TITLE
How to use bearembed --test?

### ISSUE THREAD

**Issue by smoothdvd** [hypraptive/bearid#4]
I try to bearembed --test chip_folder or bearembed --test chip_folder/face_chip.xml
always get 
```
Give a xml chip file  as input.  It should list chips and labels to be
used to learn to distinguish between these labels with metric learning.  
For example:
   ./bearembed <xml_file>
```

**Comment by ejmiller2** [comment]
For testing, you need to specify your trained network:

`bearembed [--anet]  --test <input_network> <chip_xml_file>`

For more info, try 
`bearembed --help`
