### ISSUE TITLE
Any interest in integrating this with the Wildbook backend?

### ISSUE THREAD

**Issue by JasonWildMe** [hypraptive/bearid#5]
We're continually investing in the architecture of our IBEIS platform for Wildbook:

https://github.com/WildbookOrg/ibeis

We use this for multiple detection and ID models for multiple species. If you wrap a system as a plugin, it then allows for execution from the Wildbook front end and REST-based access.

Any interest in wrapping your work as a plugin and taking advantage of our pipeline in Wildbook?

Thanks,
Jason Holmberg
Wild Me/Wildbook
jason@wildme.org

**Comment by ejmiller2** [comment]
There's definitely interest in integrating with WildBook. We don't have any of this implemented as a cloud service yet. We would be happy to explore how we can do this.

**Comment by ejmiller2** [comment]
Will follow up by email. Closing this issue.
